[package]
name = "game-server-programming-by-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[example]]
name = "a1_prime_number_multithreaded"
path = "ch1/a1_prime_number_multithreaded.rs"
